// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightliftingList.Models;

namespace WeightliftingList.Migrations
{
    [DbContext(typeof(WeightliftingListContext))]
    [Migration("20200601153916_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeightliftingList.Models.Weight", b =>
                {
                    b.Property<int>("WeightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Material");

                    b.Property<int>("Pounds");

                    b.Property<string>("WeightType");

                    b.HasKey("WeightId");

                    b.ToTable("Weights");

                    b.HasData(
                        new
                        {
                            WeightId = 1,
                            Brand = "Rogue Fitness",
                            Material = "Steel",
                            Pounds = 45,
                            WeightType = "Barbell"
                        },
                        new
                        {
                            WeightId = 2,
                            Brand = "Rogue Fitness",
                            Material = "Steel",
                            Pounds = 25,
                            WeightType = "Dumbbell"
                        },
                        new
                        {
                            WeightId = 3,
                            Brand = "Rogue Fitness",
                            Material = "Coated Steel",
                            Pounds = 40,
                            WeightType = "Kettlebell"
                        },
                        new
                        {
                            WeightId = 4,
                            Brand = "Rogue Fitness",
                            Material = "Steel",
                            Pounds = 20,
                            WeightType = "Ez Curl Bar"
                        },
                        new
                        {
                            WeightId = 5,
                            Brand = "Rogue Fitness",
                            Material = "Steel",
                            Pounds = 55,
                            WeightType = "Deadlift Bar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
