// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeightliftingList.Models;

namespace WeightliftingList.Migrations
{
    [DbContext(typeof(WeightliftingListContext))]
    partial class WeightliftingListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WeightliftingList.Models.Weight", b =>
                {
                    b.Property<int>("WeightId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brand");

                    b.Property<string>("Material");

                    b.Property<int>("Pounds");

                    b.Property<string>("WeightType");

                    b.HasKey("WeightId");

                    b.ToTable("Weights");
                });
#pragma warning restore 612, 618
        }
    }
}
